### ISSUE TITLE
Request the development of this package for Nuxt JS and SSR mode 

### ISSUE THREAD

**Issue by Qualima** [vue-a11y/vue-dark-mode#4]
Hello dear friend, this package can be given much more attention and use, If you develop this package optimally for powerful and widely used **Nuxt JS** frameworks, many Vue projects will be developed by Nuxt JS Framework. Please Optimize this plugin for Nuxt JS and SSR Mode , thank you....

**Comment by ktquez** [comment]
Hello @Qualima , thank you for your feedback.

Yes, it is in our plans to support SSR, however Nuxt.js has an official module with the same purpose.
https://darkmode.vue-a11y.com/howto/nuxt.html

**Comment by ktquez** [comment]
Hi @Qualima, what's up?

[v1](https://github.com/vue-a11y/vue-dark-mode/releases/tag/v1.0.0) has been released, now with [SSR support](https://darkmode.vue-a11y.com/howto/ssr.html) and more features and fixes.

Any errors or feedback in use, let me know.
